### ISSUE TITLE
Add XQuartz

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/staged-recipes#2587]
Adding this todo for later. IIUC this amounts to adding [xorg-server]( https://github.com/XQuartz/xorg-server ), which they [explain]( https://www.xquartz.org/Developer-Info.html#xorg-server ) how to build. They also include a [build script]( https://github.com/XQuartz/build-support/blob/master/compile-xserver.sh ), which may be of use. Also [quartz-wm]( https://github.com/XQuartz/quartz-wm ) is probably needed to have some Window Manager. Hopefully this isn't too bad especially since we have all the X11 libraries thanks to @pkgw.

**Comment by epruesse** [comment]
Looking at the Macports [portfile](https://trac.macports.org/browser/trunk/dports/x11/xorg-server/Portfile), we need

requirements / build:
   - [ ] pkg-config
   - [ ] mesa
   - [ ] xorg-applewmproto 
   - [ ] xorg-bigreqsproto
   - [ ] xorg-damageproto
   - [ ] xorg-fixesproto
   - [ ] xorg-fontsproto
   - [ ] xorg-glproto
   - [ ] xorg-inputproto
   - [ ] xorg-presentproto
   - [ ] xorg-randrproto
   - [ ] xorg-recordproto
   - [ ] xorg-renderproto
   - [ ] xorg-resourceproto
   - [ ] xorg-scrnsaverproto
   - [ ] xorg-videoproto
   - [ ] xorg-xcmiscproto
   - [ ] xorg-xproto
   - [ ] xorg-xextproto
   - [ ] xorg-xineramaproto
   - [ ] xorg-xtrans
   - [ ] xorg-util-macros
   - [ ] xorg-font-util

requirements/run:
   - [ ] xinit
   - [ ] quartz-wm
   - [ ] xorg-fonts
   - [ ] xkeyboard-config
   - [ ] libpixman
   - [ ] xorg-libxkbfile
   - [ ] xorg-libXfont
   - [ ] xorg-libXt
   - [ ] xorg-libAppleWM
   - [ ] xorg-libXfixes

**Comment by jakirkham** [comment]
Thanks for putting this list together @epruesse.

Couple of questions. First, just to verify, checked means feedstock with packages? Second are there any of these that have open PRs associated? If so, it might be helpful to include the links in the list.

Also for `libpixman`, I believe we call it [`pixman`]( https://github.com/conda-forge/pixman-feedstock ) unless I'm missing a subtle distinction being made here.

**Comment by pkgw** [comment]
Yes, I believe that `pixman` provides what XQuartz would need.

**Comment by epruesse** [comment]
@jakirkham Yes, checks means package is available. I didn't check for open PRs - this was more to get a list of things that definitely need to be there first. Since the build requirements seem to be all *proto, which in X.org lingo refers to header only libs / API definitions, they should be easy enough to add. Is it ok to bundle them in one PR?

**Comment by epruesse** [comment]
PR #2817  adds 26 xorg*proto packages -- that's all but the two DRI ones.

**Comment by jakirkham** [comment]
Wow! Thanks @epruesse.

**Comment by jakirkham** [comment]
> Is it ok to bundle them in one PR?

The only challenge is being able to hold someone's attention span long enough to review them all in one go. That said, we can always use that PR as a starting point and pull out individual recipes into separate PRs after checking them.

**Comment by epruesse** [comment]
@jakirkham These are the "protocol" packages. They contain nothing but one or two header files, sometimes an xml file, and a pc (pkg-config) file. So it's all the same. If you diff two packages you'll see the only difference is in name/version/sha256.

**Comment by epruesse** [comment]
I was debating whether to keep them in individual packages at all. But since X.org has them that way and the Distros seem to follow (e.g. xorg-printproto's "Print.h" is in Debian in x11proto-print-dev), I figured I'd just create 26 packages at once... They build very quickly, nothing much to do.

**Comment by epruesse** [comment]
I've got a little further on this (see [here](https://github.com/epruesse/staged-recipes/tree/xorg-xserver/recipes)). Build seems to work, but I can't test missing two major run time components: xorg-fonts and xkeyboard-config. The later unfortunately requires perl-xml-parser, which in turn requires quite a few perl packages. They are available in bioconda, though, so I could "merge" them into conda-forge. We're talking another two dozen packages though.

@conda-forge/core @bgruening Are there any plans WRT perl in conda-forge / migration of perl packages from bioconda to here?

@jakirkham The topic here may as well become "Xquartz and Xwin" -- both are the relevant pieces missing to get X11 apps actually running on non-Linux platforms w/o non-conda installs.

**Comment by bgruening** [comment]
@ebolyen no plans yet. But we are happy to help as we did with the R packages. However, currently we are still busy with the R story and it is yet not clear howto update them. So I think we should solve this question before we start another bulk migration.

**Comment by epruesse** [comment]
@jakirkham What do you think I should do re xkeyboard-config? Without that package, XQuartz will compile but not work properly.

Options:
 1. Create a "port perl" ticket and defer this ticket until after that has completed
 2. Port the required perl packages from bioconda
 3. Perl is only needed during build I believe, so I could hack around this by
    a. Installing Perl+Modules from bioconda in build.sh
    b. Installing Perl+Modules from CPAN in build.sh

**Comment by jakirkham** [comment]
By the R update story, @bgruening, are you referring to how things are pinned? ( https://github.com/conda-tools/conda-build-all/pull/86 ) Or are there other issues?

Sorry for the long delay here, @epruesse. Porting perl packages seems like the right thing to do. Though you would know best what sort of timeline this should happen on.

**Comment by epruesse** [comment]
@jakirkham Well, I'm pondering whether I should wait for conda-build 3.* to make it into conda-forge before I create any more packages.

**Comment by jakirkham** [comment]
What features are you hoping to use from `conda-build` 3 that might make this easier?

**Comment by epruesse** [comment]
The pinning and the outputs mainly. I've run into too many issues with conda pulling the wrong packages and am really hoping those things were addressed in the 3.

**Comment by epruesse** [comment]
W.r.t #539 -- it's not just XQuartz, but also Xwin and Xvfb that would be desirable to have in conda directly. Xvfb in particular, as that would allow testing X based software during package build.

**Comment by jakirkham** [comment]
Better pinning will be nice. Though I don't think this will replace the need for an ABI tracker and some manual tweaks. Semantic versioning is still not used often enough still.

I agree. We want working X11 on all platforms. Was just trying to address the PR author's motivations, which hinged around getting XQuartz on macOS.

**Comment by zklaus** [comment]
Hey, just stumbled across this again with another rebuild. @epruesse, @jakirkham would you be interested in a renewed effort, now that conda-build 3 is available?

**Comment by epruesse** [comment]
XQuartz itself also has had a some updates recently after a long period of inactivity. I just don't think I can devote much time, if any. I'm just too swamped...

**Comment by zklaus** [comment]
@epruesse, completely understandable! Do you think you might be able to put together/update a "battle plan" as in https://github.com/conda-forge/staged-recipes/issues/2587#issuecomment-293111507 so that we can make some progress in the right direction with the bits and pieces?

**Comment by epruesse** [comment]
I've got some tbb issues on SINA and the arb-bio package (both bioconda) to fix first, and this weekend is already full, so it would take too long until I got around to it (especially since by then I'm sure the next crisis has popped into my schedule...)

**Comment by jakirkham** [comment]
Checked some completed boxes above. Appears other dependencies got worked out in the interim

Elmar had referred to MacPorts as a reference before. It appears they moved from their own SVN setup to GitHub. This appears to be [the current recipe]( https://github.com/macports/macports-ports/blob/master/x11/xorg-server/Portfile )

Also added some notes for `xset` based on a quick search

Hope that is helpful
