### ISSUE TITLE
examples break build-locally.py

### ISSUE THREAD

**Issue by bernt-matthias** [conda-forge/staged-recipes#27695]
### Bug:

Because of the example reciped in https://github.com/conda-forge/staged-recipes/tree/main/recipes, one gets 
```
...
+ echo 'Building all recipes'
Building all recipes
+ python /home/conda/staged-recipes-copy/.ci_support/build_all.py
Traceback (most recent call last):
  File "/home/conda/staged-recipes-copy/.ci_support/build_all.py", line 340, in <module>
    build_all(os.path.join(root_dir, "recipes"), args.arch)
  File "/home/conda/staged-recipes-copy/.ci_support/build_all.py", line 97, in build_all
    raise ValueError("Mixing meta.yaml and recipe.yaml recipes is not supported")
ValueError: Mixing meta.yaml and recipe.yaml recipes is not supported
Traceback (most recent call last):
  File "/home/berntm/projects/conda-forge/staged-recipes/build-locally.py", line 101, in <module>
    main()
  File "/home/berntm/projects/conda-forge/staged-recipes/build-locally.py", line 95, in main
    run_docker_build(ns)
  File "/home/berntm/projects/conda-forge/staged-recipes/build-locally.py", line 33, in run_docker_build
    subprocess.check_call([script])
  File "/usr/lib/python3.10/subprocess.py", line 369, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['.scripts/run_docker_build.sh']' returned non-zero exit status 1.
```

when running `python build-locally.py linux64`.

**Comment by wolfv** [comment]
@bernt-matthias I opened a PR that could fix it: #27803 

Would you be able to try this?

**Comment by wolfv** [comment]
Fixed! Thank you @bernt-matthias for testing!

**Comment by apmorton** [comment]
Am I missing something? I still get this failure using build-locally.py
